### ISSUE TITLE
Request for updating the HF demo code

### ISSUE THREAD

**Issue by chongzhou96** [camenduru/EdgeSAM-hf#1]
Hi camenduru,

Thanks for implementing a colab script for EdgeSAM. We just updated the EdgeSAM HF demo code for better inference efficiency. Would you consider pulling the latest code from the HF repo (https://huggingface.co/spaces/chongzhou/EdgeSAM)?

Thanks!

**Comment by camenduru** [comment]
I updated the code, thanks ❤
